# Generated by Django 4.1.2 on 2022-10-20 00:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='students_courses', through='course.CourseRelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
