# Generated by Django 4.1.2 on 2022-11-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_courserelation_user_courserelation_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='requirements',
            field=models.TextField(default='a', verbose_name='Requirements'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='what_you_will_learn',
            field=models.TextField(default='a', verbose_name='What you will learn'),
            preserve_default=False,
        ),
    ]
