# Generated by Django 4.1.2 on 2022-11-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_requirements_course_what_you_will_learn'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='courserelation',
            constraint=models.UniqueConstraint(fields=('creator', 'course'), name='unique course relation'),
        ),
    ]
