# Generated by Django 4.1.2 on 2022-11-16 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_courserelation_unique course relation'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='courserelation',
            name='unique course relation',
        ),
        migrations.AddConstraint(
            model_name='courserelation',
            constraint=models.UniqueConstraint(fields=('creator', 'course'), name='unique course relation', violation_error_message='You already rated this course.'),
        ),
    ]
