# Generated by Django 4.1.2 on 2022-11-16 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_course_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courserelation',
            name='current_lesson',
        ),
    ]
