# Generated by Django 4.1.2 on 2022-11-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_course_image'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='courserelation',
            name='unique course relation',
        ),
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.AddConstraint(
            model_name='courserelation',
            constraint=models.UniqueConstraint(fields=('creator', 'course'), name='unique course relation'),
        ),
    ]
