# Generated by Django 4.1.2 on 2022-12-04 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_remove_courserelation_unique course relation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
    ]
