# Generated by Django 4.1.2 on 2022-11-08 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_courserelation_user_courserelation_creator'),
        ('action', '0005_remove_action_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
            preserve_default=False,
        ),
    ]
