# Generated by Django 4.1.2 on 2022-11-16 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0006_action_course'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='action',
            constraint=models.UniqueConstraint(fields=('creator', 'content_type', 'object_id', 'action', 'course'), name='unique action'),
        ),
    ]
