# Generated by Django 4.1.2 on 2022-11-16 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0007_action_unique action'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='action',
            name='unique action',
        ),
        migrations.AddConstraint(
            model_name='action',
            constraint=models.UniqueConstraint(fields=('creator', 'content_type', 'object_id', 'action', 'course'), name='unique action', violation_error_message='This action already exists'),
        ),
    ]
