# Generated by Django 4.1.2 on 2022-11-18 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='max_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
