# Generated by Django 4.1.2 on 2022-11-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quizrelation_quizrelation_unique quiz relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizrelation',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
