# Generated by Django 4.1.2 on 2022-11-25 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_remove_courserelation_unique course relation_and_more'),
        ('quiz', '0005_quizrelation_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions_quiz', to='course.course'),
            preserve_default=False,
        ),
    ]
