# Generated by Django 4.1.2 on 2022-11-25 19:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_quiz_pass_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_response',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
