# Generated by Django 4.1.2 on 2022-11-17 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_alter_lesson_video_duration_alter_lesson_video_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('order',)},
        ),
    ]
