# Generated by Django 4.1.2 on 2022-11-22 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lesson', '0003_alter_lesson_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonrelation',
            name='user',
        ),
        migrations.AddField(
            model_name='lessonrelation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation Date and Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonrelation',
            name='creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AddField(
            model_name='lessonrelation',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time'),
        ),
    ]
