# Generated by Django 4.1.2 on 2022-11-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0001_initial'),
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='action',
            field=models.ManyToManyField(to='action.action'),
        ),
    ]
