# Generated by Django 4.1.2 on 2022-11-07 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_rating_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='action',
        ),
    ]
