# Generated by Django 4.1.2 on 2022-11-16 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0004_alter_rating_rating_rating_unique rating'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rating',
            name='unique rating',
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('creator', 'course'), name='unique rating', violation_error_message='You already rated this course.'),
        ),
    ]
