# Generated by Django 4.1.2 on 2022-11-02 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_bookmark_note_alter_content_content_type_taggeditem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='TaggedItem',
        ),
    ]
