# Generated by Django 4.1.2 on 2022-11-17 17:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('content', '0003_delete_bookmark_delete_note_delete_taggeditem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ('order',)},
        ),
    ]
