# Generated by Django 4.1.2 on 2022-10-22 14:32

from django.db import migrations, models
import django.db.models.deletion
import udemy.apps.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0004_alter_course_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('order', udemy.apps.core.fields.OrderField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='course.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
