# Generated by Django 4.1.2 on 2022-12-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_modelrelatedobject_model_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltest',
            name='num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
