# Generated by Django 4.1.2 on 2022-12-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_modeltest_options_modeltest_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelrelatedobject',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='modelrelatedobject',
            name='order',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
