# Generated by Django 4.1.2 on 2022-12-03 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_modelrelatedobject_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modeltest',
            options={},
        ),
        migrations.RemoveField(
            model_name='modeltest',
            name='order',
        ),
    ]
