# Generated by Django 4.1.2 on 2022-11-02 19:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0002_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='answer_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.TextField(),
        ),
    ]
