# Generated by Django 4.1.2 on 2022-11-04 16:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0004_remove_answer_user_remove_question_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='liked_by',
            field=models.ManyToManyField(related_name='questions_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
