# Generated by Django 4.1.2 on 2022-11-05 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0001_initial'),
        ('question', '0006_question_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='liked_by',
        ),
        migrations.RemoveField(
            model_name='question',
            name='liked_by',
        ),
        migrations.AddField(
            model_name='answer',
            name='action',
            field=models.ManyToManyField(to='action.action'),
        ),
        migrations.AddField(
            model_name='question',
            name='action',
            field=models.ManyToManyField(to='action.action'),
        ),
    ]
