# Generated by Django 4.1.2 on 2022-11-05 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_courserelation_user_courserelation_creator'),
        ('question', '0007_remove_answer_liked_by_remove_question_liked_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='course.course'),
            preserve_default=False,
        ),
    ]
