# Generated by Django 4.1.2 on 2022-11-07 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_answer_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='action',
        ),
        migrations.RemoveField(
            model_name='question',
            name='action',
        ),
    ]
