# Generated by Django 4.1.2 on 2022-11-07 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0009_remove_answer_action_remove_question_action'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
